title: WAN's THOUGHT
description: Wanda Ichsanul Isra's thought

url: https://wlisrausr.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /
 - title: About
   url: /about
 - title: Contact
   url: /contact
 - title: Search
   url: /search

social:
   github: wlisrausr
   stackoverflow: 7152771/wlisrausr
   email: wandaisra@gmail.com
   linkedin: wlisrausr

google_analytics: "UA-58263416-1"
