title: Wanda Ichsanul Isra
description: Wanda Ichsanul Isra's blog that related to his geek life

url: https://wlisrausr.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: wlisrausr
   twitter: wlisrausr
   facebook: wlisrausr
   email: wandaisra@gmail.com

google_analytics: "UA-58263416-1"
