title: Pragmatic Life
description: Wanda Ichsanul Isra's pragmatic life

url: https://wlisrausr.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: About
   url: /about
 - title: Contact
   url: /contact
 - title: Categories
   url: /categories
 - title: Search
   url: /search

social:
   github: wlisrausr
   stackoverflow: 7152771/wlisrausr
   email: wandaisra@gmail.com
   linkedin: wlisrausr

google_analytics: "UA-58263416-1"
